logging:
  level:
    root: INFO
  path: ../logs/
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/hml
    enabled: true
    encoding: UTF-8
  profiles:
    active: dev
server:
  port: 8080
  ip: localhost

